[package]
name = "hocon-ls"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
hocon-rs = { path = "../hocon-rs" }
lsp-server = "0.7.6"
serde = "1.0.197"
serde_json = "1.0.115"
lsp-types = "=0.95"
